name: Trivy image scan (manual)

on:
  workflow_dispatch:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Trivy (action)
        uses: aquasecurity/trivy-action@v0.33.1
        with:
          image-ref: 'docker.io/grpc/php:latest'
          scan-type: 'image'
          exit-code: '1'        # вернёт код 1 при обнаружении указанных severity
          severity: 'CRITICAL'  # интересуют только критические уязвимости
          format: 'table'
          output: 'trivy-results.txt'

      - name: Show Trivy output
        if: always()
        run: |
          echo "=== Trivy results ==="
          [ -f trivy-results.txt ] && cat trivy-results.txt || echo "No output file"
